spring:
  webflux:
    base-path: "/"
  r2dbc.url: "r2dbc:postgresql://postgres@devices-registry-db:5432/postgres"
server:
  error:
    include-message: "always"
logging.level.org.springframework: WARN